### ISSUE TITLE
ignore - "Private Storage File Not Available" when I run in IDE

### ISSUE THREAD

**Issue by ariettag** [5-pengoo/Therabot#12]
`--- javafx-maven-plugin:0.0.5:run (default-cli) @ Therabot ---
Aug 08, 2021 10:50:33 AM com.gluonhq.attach.util.Platform <clinit>
INFO: javafx.platform is not defined. Desktop will be assumed by default.
Aug 08, 2021 10:50:33 AM com.gluonhq.attach.util.impl.DefaultServiceFactory createInstance
WARNING: No new instance for interface com.gluonhq.attach.display.DisplayService and class com.gluonhq.attach.display.impl.DesktopDisplayService
Aug 08, 2021 10:50:34 AM com.gluonhq.attach.util.impl.DefaultServiceFactory createInstance
WARNING: No new instance for interface com.gluonhq.attach.display.DisplayService and class com.gluonhq.attach.display.impl.DesktopDisplayService
Aug 08, 2021 10:50:34 AM com.gluonhq.attach.util.impl.DefaultServiceFactory createInstance
WARNING: No new instance for interface com.gluonhq.attach.display.DisplayService and class com.gluonhq.attach.display.impl.DesktopDisplayService
Aug 08, 2021 10:50:34 AM com.gluonhq.attach.util.impl.DefaultServiceFactory createInstance
WARNING: No new instance for interface com.gluonhq.attach.storage.StorageService and class com.gluonhq.attach.storage.impl.DesktopStorageService
Aug 08, 2021 10:50:34 AM com.gluonhq.impl.charm.glisten.license.LicenseManager <clinit>
SEVERE: null
java.io.IOException: Private storage file not available
	at com.gluonhq.impl.charm.glisten.license.LicenseManager.lambda$static$0(LicenseManager.java:36)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.gluonhq.impl.charm.glisten.license.LicenseManager.<clinit>(LicenseManager.java:36)
	at com.gluonhq.charm.glisten.application.MobileApplication.continueInit(MobileApplication.java:262)
	at com.gluonhq.charm.glisten.application.MobileApplication.lambda$start$0(MobileApplication.java:230)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

Aug 08, 2021 10:50:34 AM com.gluonhq.attach.util.impl.DefaultServiceFactory createInstance
WARNING: No new instance for interface com.gluonhq.attach.storage.StorageService and class com.gluonhq.attach.storage.impl.DesktopStorageService
Aug 08, 2021 10:50:34 AM com.gluonhq.impl.charm.glisten.tracking.TrackingManager <clinit>
SEVERE: null
java.io.IOException: Private storage file not available
	at com.gluonhq.impl.charm.glisten.tracking.TrackingManager.lambda$static$0(TrackingManager.java:28)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.gluonhq.impl.charm.glisten.tracking.TrackingManager.<clinit>(TrackingManager.java:28)
	at com.gluonhq.charm.glisten.application.MobileApplication.continueInit(MobileApplication.java:266)
	at com.gluonhq.charm.glisten.application.MobileApplication.lambda$start$0(MobileApplication.java:230)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
`

**Comment by ariettag** [comment]
Actually, this might be my fault. Looks like my attempts to pull to my NetBeans project are unsuccessful. I will check back if the error is prolonged.
