### ISSUE TITLE
Error when compiling `mvn -Pios gluonfx:build`

### ISSUE THREAD

**Issue by ariettag** [5-pengoo/Therabot#14]
Hi  @jperedadnr,
This error only occurs with `mvn -Pios gluonfx:build`, not `mvn gluonfx:runagent`, `mvn clean -U javafx:run`, or `mvn javafx:run`. I have not tried `mvn -Pios gluonfx:nativerun`, obviously.

```
[Sun Aug 08 18:00:15 PDT 2021][INFO] We will now compile your code for arm64-apple-ios. This may take some time.
[Sun Aug 08 18:00:21 PDT 2021][INFO] [SUB] [com.mysecondapplication.mysecondapplication:6829]    classlist:   3,394.02 ms,  0.96 GB
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] [com.mysecondapplication.mysecondapplication:6829]        setup:     852.13 ms,  0.96 GB
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] Error: Error parsing JNI configuration in file:/Users/superpengooooo/NetBeansProjects/Therabot/target/classes/META-INF/native-image/jni-config.json:
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] Could not resolve org.graalvm.nativebridge.jni.JNIExceptionWrapperEntryPoints for reflection configuration. Reason: java.lang.ClassNotFoundException: org.graalvm.nativebridge.jni.JNIExceptionWrapperEntryPoints. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationResources.
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Error parsing JNI configuration in file:/Users/superpengooooo/NetBeansProjects/Therabot/target/classes/META-INF/native-image/jni-config.json:
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] Could not resolve org.graalvm.nativebridge.jni.JNIExceptionWrapperEntryPoints for reflection configuration. Reason: java.lang.ClassNotFoundException: org.graalvm.nativebridge.jni.JNIExceptionWrapperEntryPoints. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationResources.
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:139)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:120)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:109)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:491)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:449)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:126)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.jni.access.JNIAccessFeature.afterRegistration(JNIAccessFeature.java:126)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$17(NativeImageGenerator.java:873)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:873)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:579)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:494)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[Sun Aug 08 18:00:22 PDT 2021][INFO] [SUB] Error: Image build request failed with exit status 1
[Sun Aug 08 18:00:22 PDT 2021][SEVERE] Process compile failed with result: 1
Check the log files under /Users/superpengooooo/NetBeansProjects/Therabot/target/gluonfx/arm64-ios/gvm/log
And please check https://docs.gluonhq.com/ for more information.
[Sun Aug 08 18:00:22 PDT 2021][INFO] Logging process [compile] to file: /Users/superpengooooo/NetBeansProjects/Therabot/target/gluonfx/log/process-compile-1628470822118.log
[Sun Aug 08 18:00:22 PDT 2021][SEVERE] Compiling failed.
Check the log files under /Users/superpengooooo/NetBeansProjects/Therabot/target/gluonfx/arm64-ios/gvm/log
And please check https://docs.gluonhq.com/ for more information.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.536 s
[INFO] Finished at: 2021-08-08T18:00:22-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.3:compile (default-cli) on project Therabot: Compiling failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.623 s
[INFO] Finished at: 2021-08-08T18:00:22-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.3:build (default-cli) on project Therabot: Error, gluonfx:build failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by jperedadnr** [comment]
It works fine for me. What is your GraalVM build? Can you use latest:

https://github.com/gluonhq/graal/releases/download/gluon-21.2.0-dev-20210621_1207/graalvm-svm-darwin-gluon-21.2.0-dev.zip

**Comment by ariettag** [comment]
@jperedadnr I changed it to the latest, and it is still giving me those errors. 

For reference, `GRAALVM_HOME` =
`/Users/superpengooooo/graalvm-svm-darwin-gluon-21.1.0-dev/Contents/Home`, and `JAVA_HOME` =
`/Users/superpengooooo/graalvm-svm-darwin-gluon-21.1.0-dev/Contents/Home`
Java version is `openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM 21.1.0-dev (build 11.0.11+5-jvmci-21.1-b03)
OpenJDK 64-Bit Server VM GraalVM 21.1.0-dev (build 11.0.11+5-jvmci-21.1-b03, mixed mode, sharing)`, although last time it was 12.0.

**Comment by jperedadnr** [comment]
You have to update GRAALVM_HOME to the new path. Make sure it has 21.2.0, and restart the terminal.

**Comment by ariettag** [comment]
@jperedadnr I forgot to say in my previous message that when I downloaded the new graalvm version, my computer blocked it from use because it is from an unidentified developer. I keep trying to allow it, but it's not letting me.
`zsh: permission denied: /Users/superpengooooo/graalvm-svm-darwin-gluon-21.2.0-dev/Contents/Home`

**Comment by jperedadnr** [comment]
On a terminal run:
```
cd /Users/superpengooooo/graalvm-svm-darwin-gluon-21.2.0-dev/
sudo xattr -r -d com.apple.quarantine .

```
Then you should be able to use it

**Comment by ariettag** [comment]
@jperedadnr it still doesn't work, both in the graalvm directory as well as when I reroute back to my project file.

**Comment by jperedadnr** [comment]
What is failing? Can you post the output of the command I mentioned before?

**Comment by ariettag** [comment]
Ok @jperedadnr, actually after some troubleshooting I was able to set `JAVA_HOME` to
`/Users/superpengooooo/graalvm-svm-darwin-gluon-21.2.0-dev/Contents/Home` and `GRAALVM_HOME` to
`/Users/superpengooooo/graalvm-svm-darwin-gluon-21.2.0-dev/Contents/Home`. However, when I run `mvn -Pios gluonfx:build`, it displays the attached pop-up, which prevents me from furthering the process. This pop-up is now displaying for any maven process that I attempt. (`mvn gluonfx:runagent`, `mvn clean -U javafx:run`,`mvn javafx:run`)

<img width="263" alt="Screen Shot 2021-08-09 at 1 27 10 PM" src="https://user-images.githubusercontent.com/79435335/128770352-1ee9d920-c7ce-41b7-beed-d047e442864a.png">

**Comment by jperedadnr** [comment]
This command I sent before:

```
cd /Users/superpengooooo/graalvm-svm-darwin-gluon-21.2.0-dev/
sudo xattr -r -d com.apple.quarantine .
```
should remove the trust issue... In fact gluonfx:build should already execute such command.

Can you try it again (copy the exact command, including the final dot (".")), and post the result?

**Comment by ariettag** [comment]
Actually, I must have missed the period "." at the end, because it works now! I do have one more non-error-related question, which I will make open an issue for now. Thank you so much!!

**Comment by ariettag** [comment]
Hello again @jperedadnr, unfortunately I'm getting a similar problem as before which is also only occuring with ```mvn -Pios gluonfx:build```, not ```mvn gluonfx:runagent```, ```mvn clean -U javafx:run,``` or ```mvn javafx:run```. See the attached log file.
[process-compile-1629567218755.log](https://github.com/5-pengoo/Therabot/files/7025946/process-compile-1629567218755.log)

**Comment by jperedadnr** [comment]
You are still using GraalVM 21.1.0
You have to remove it and then set the default `GRAALVM_HOME` to 21.2.0
Check your ~/.bash_profile file, you might have set it there.

**Comment by ariettag** [comment]
Ok, that fixed it @jperedadnr. Thank you!
